# Generated by Django 3.1.6 on 2021-02-04 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0004_auto_20210204_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='full_name',
            field=models.TextField(verbose_name='Имя'),
        ),
    ]
